#file: noinspection SpellCheckingInspection
name: CI
on:
  - push
    
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Build
        run: dotnet build --configuration Release
        
      - name: Test
        run: dotnet test --configuration Release --no-build